#!/bin/bash

DIAMOND_FILE=${1:-diamond.json}

npx hardhat diamond:deploy --new --o $DIAMOND_FILE;
npx hardhat diamond:add --local --name MyToken --o $DIAMOND_FILE;
npx hardhat diamond:add --local --name VotingPowerFacet --o $DIAMOND_FILE --links LibVotingPower;
npx hardhat diamond:add --local --name TreasuryDefaultCallbackHandlerFacet --o $DIAMOND_FILE;
npx hardhat diamond:add --local --name TreasuryVotingFacet --o $DIAMOND_FILE --links LibVotingPower;
npx hardhat diamond:add --local --name TreasuryViewerFacet --o $DIAMOND_FILE;